# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/postgres

- name: Créer réseau backend
  community.docker.docker_network:
    name: backend

- name: Créer dossier stack PostgreSQL
  ansible.builtin.file:
    path: /opt/stacks/postgres
    state: directory
    mode: '0755'

- name: Copier stack Docker Compose PostgreSQL
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/stacks/postgres/compose.yml
    mode: '0644'

- name: Déployer stack PostgreSQL
  community.docker.docker_compose_v2:
    project_src: /opt/stacks/postgres
    pull: always
