# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/shaarli

- name: Créer dossier stack Shaarli
  ansible.builtin.file:
    path: /opt/stacks/shaarli
    state: directory
    mode: '0755'

- name: Copier stack Docker Compose Shaarli
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/stacks/shaarli/compose.yml
    mode: '0644'

- name: Déployer stack Shaarli
  community.docker.docker_compose_v2:
    project_src: /opt/stacks/shaarli
    pull: always
