#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/portainer

- name: Créer dossier stack Portainer
  ansible.builtin.file:
    path: /opt/stacks/portainer
    state: directory
    mode: '0755'

- name: Copier stack Docker Compose Portainer
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/stacks/portainer/compose.yml
    mode: '0644'

- name: Déployer stack Portainer
  community.docker.docker_compose_v2:
    project_src: /opt/stacks/portainer
    pull: always
