#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/portainer
- name: Créer volume Portainer
  community.docker.docker_volume:
    name: portainer_data

- name: Lancer Portainer
  community.docker.docker_container:
    name: portainer
    recreate: true
    image: portainer/portainer-ce:latest
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - name: web
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: "Host(`{{ portainer_domain }}`)"
      traefik.http.routers.portainer.entrypoints: "websecure"
      traefik.http.routers.portainer.tls.certresolver: "myresolver"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
