#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/traefik

- name: Créer réseau Docker
  community.docker.docker_network:
    name: web

- name: Créer dossier stack Traefik
  ansible.builtin.file:
    path: /opt/stacks/traefik
    state: directory
    mode: '0755'

- name: Créer dossier letsencrypt
  ansible.builtin.file:
    path: /opt/stacks/traefik/letsencrypt
    state: directory
    mode: '0755'

- name: Créer fichier acme.json
  ansible.builtin.file:
    path: /opt/stacks/traefik/letsencrypt/acme.json
    state: touch
    mode: '0600'

- name: Copier stack Docker Compose Traefik
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/stacks/traefik/compose.yml
    mode: '0644'

- name: Déployer stack Traefik
  community.docker.docker_compose_v2:
    project_src: /opt/stacks/traefik
    pull: always
