---
- name: Installer et configurer Docker sur Debian
  hosts: all
  become: true
  gather_facts: true

  vars:
    docker_packages_to_remove:
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
      - containerd
      - runc

    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  tasks:

    - name: Supprimer les anciens paquets Docker
      ansible.builtin.apt:
        name: "{{ docker_packages_to_remove }}"
        state: absent
        purge: true

    - name: Installer les dépendances
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: true

    - name: Créer le dossier keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Vérifier si la clé existe
      ansible.builtin.stat:
        path: /etc/apt/keyrings/docker.asc
      register: docker_gpg_key

    - name: Télécharger la clé GPG Docker si absente
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
      when: not docker_gpg_key.stat.exists

    - name: Ajouter le dépôt Docker
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.sources
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/debian
          Suites: {{ ansible_distribution_release }}
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc

    - name: Mettre à jour le cache APT
      ansible.builtin.apt:
        update_cache: true

    - name: Installer Docker
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: present

    - name: Démarrer et activer Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Ajouter l'utilisateur au groupe docker
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Vérifier la version de Docker
      ansible.builtin.command: /usr/bin/docker --version
      register: docker_version
      changed_when: false

    - name: Afficher la version de Docker
      ansible.builtin.debug:
        msg: "{{ docker_version.stdout }}"
