# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/wallabag

- name: Créer dossier stack Wallabag
  ansible.builtin.file:
    path: /opt/stacks/wallabag
    state: directory
    mode: '0755'

- name: Copier stack Docker Compose Wallabag
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/stacks/wallabag/compose.yml
    mode: '0644'

- name: Déployer stack Wallabag
  community.docker.docker_compose_v2:
    project_src: /opt/stacks/wallabag
    pull: always
