# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/wireguard

- name: Créer dossier stack WireGuard
  ansible.builtin.file:
    path: /opt/stacks/wireguard
    state: directory
    mode: '0755'

- name: Créer dossier config WireGuard
  ansible.builtin.file:
    path: /opt/wireguard/config
    state: directory
    mode: '0755'

- name: Copier stack Docker Compose WireGuard
  ansible.builtin.template:
    src: compose.yml.j2
    dest: /opt/stacks/wireguard/compose.yml
    mode: '0644'

- name: Déployer stack WireGuard
  community.docker.docker_compose_v2:
    project_src: /opt/stacks/wireguard
    pull: always
